services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiktok-api:latest
    container_name: tiktok-system_be
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}